name: "DevOps Scripts"
description: "Provides access to vm2.DevOps bash scripts for CI/CD workflows"
author: "Val Melamed"

runs:
  using: "composite"
  steps:
    - name: Setup DevOps scripts
      shell: bash
      env:
        VERBOSE: ${{ vars.VERBOSE || false }}
      run: |
        # Determine the lib directory path relative to the action
        ACTIONS_DIR=$(realpath "${{ github.action_path }}")
        LIB_DIR=$(realpath "$ACTIONS_DIR/../../../scripts/bash/lib")

        source "$LIB_DIR/gh_core.sh"

        # Add both scripts and lib directories to PATH for the remainder of the workflow
        echo "$ACTIONS_DIR" >> $GITHUB_PATH
        echo "$LIB_DIR" >> $GITHUB_PATH

        trace "Added $ACTIONS_DIR and $LIB_DIR to GITHUB_PATH:"
        trace "ACTIONS_DIR: $ACTIONS_DIR"
        trace "LIB_DIR: $LIB_DIR"

        # Export the directories for reference
        echo "DEVOPS_SCRIPTS_DIR=$ACTIONS_DIR" >> $GITHUB_ENV
        echo "DEVOPS_LIB_DIR=$LIB_DIR" >> $GITHUB_ENV

        trace "Exported DEVOPS_SCRIPTS_DIR and DEVOPS_LIB_DIR environment variables:"
        trace "DEVOPS_SCRIPTS_DIR: $DEVOPS_SCRIPTS_DIR"
        trace "DEVOPS_LIB_DIR: $DEVOPS_LIB_DIR"

        echo "✅ DevOps scripts and libraries are now available in PATH"
