name: "DevOps Scripts"
description: "Provides access to vm2.DevOps bash scripts for CI/CD workflows"
author: "Val Melamed"

runs:
  using: "composite"
  steps:
    - name: Setup DevOps scripts
      shell: bash
      run: |
        # Make scripts executable
        chmod +x "${{ github.action_path }}/*.sh"

        # Add scripts directory to PATH for the remainder of the workflow
        echo "${{ github.action_path }}" >> $GITHUB_PATH

        # Export the scripts directory for reference
        echo "DEVOPS_SCRIPTS_DIR=${{ github.action_path }}" >> $GITHUB_ENV

        echo "✅ DevOps scripts are now available in PATH"
