#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Val Melamed

set -euo pipefail

script_name=$(basename "${BASH_SOURCE[0]}")
script_dir=$(dirname "$(realpath -e "${BASH_SOURCE[0]}")")
lib_dir=$(realpath -e "$script_dir/../../scripts/bash/lib")

declare -xr script_name
declare -xr script_dir
declare -xr lib_dir

# shellcheck disable=SC1091 # Not following
source "$lib_dir/gh_core.sh"

declare -xri success
declare -xri failure
declare -xri err_tool_error
declare -xri err_logic_error
declare -xri err_argument_value
declare -xri err_missing_argument
declare -xri err_too_many_arguments
declare -xri err_unknown_argument

declare -x _ignore

declare -xr default_minver_tag_prefix

declare -xri default_repeat=10

declare -x benchmark_project=""
declare -xi repeat=${REPEAT:-$default_repeat}
declare -x preprocessor_symbols=${PREPROCESSOR_SYMBOLS:-}
declare -x minver_tag_prefix=${MINVERTAGPREFIX:-"$default_minver_tag_prefix"}
declare -x minver_prerelease_id=${MINVERDEFAULTPRERELEASEIDENTIFIERS:-}
declare -x bencher_project=${BENCHER_PROJECT:-}
declare -x bencher_testbed=${BENCHER_TESTBED:-}
declare -x bencher_branch=${BENCHER_BRANCH:-"main"}
declare -x bencher_adapter=${BENCHER_ADAPTER:-"c_sharp_dot_net"}

source "$script_dir/rebuild-bench-history-run.usage.sh"
source "$script_dir/rebuild-bench-history-run.args.sh"

get_arguments "$@"
benchmark_project=${benchmark_project:-"${BENCHMARK_PROJECT:-}"}

# Determine the benchmark projects: the explicit one if given, otherwise discover every *.csproj under benchmarks/
# recursively, pruning generated bin/obj/BenchmarkDotNet.Artifacts so BenchmarkDotNet's autogenerated projects are ignored.
declare -a benchmark_projects=()
if [[ -n "$benchmark_project" ]]; then
    is_safe_existing_path "$benchmark_project" || true
    benchmark_projects=("$benchmark_project")
elif [[ -d benchmarks ]]; then
    readarray -t benchmark_projects < <(
        find benchmarks \
            -type d \( -name bin -o -name obj -o -name BenchmarkDotNet.Artifacts \) -prune \
            -o -name '*.csproj' -print | sort)
fi
(( ${#benchmark_projects[@]} > 0 )) || error -ec "$err_argument_value" "No benchmark projects found under 'benchmarks/' and none specified."

# Validate the rest of the inputs (accumulate all problems, then bail once).
validate_preprocessor_symbols preprocessor_symbols                        || true
validate_semverTagComponents "$minver_tag_prefix" "$minver_prerelease_id" || true
[[ $bencher_project =~ ^[a-zA-Z_][a-zA-Z0-9_.-]*$ ]]                      || error -ec "$err_argument_value" "The Bencher project '$bencher_project' is not a valid project name (slug)."
[[ $bencher_testbed =~ ^[a-zA-Z_][a-zA-Z0-9_.-]*$ ]]                      || error -ec "$err_argument_value" "The Bencher testbed '$bencher_testbed' is not a valid testbed name."
validate_branch_name "$bencher_branch"                                    || true
is_variable_name "$bencher_adapter"                                       || error -ec "$err_argument_value" "The Bencher adapter '$bencher_adapter' is not a valid adapter name."
is_safe_integer "$repeat"                                                 || true
(( repeat >= 1 ))                                                         || error -ec "$err_argument_value" "repeat must be a positive integer (got '$repeat')."
[[ -n "$bencher_project" ]]                                               || error -ec "$err_missing_argument" "Bencher project (--bencher-project) is required."
[[ -n "$bencher_testbed" ]]                                               || error -ec "$err_missing_argument" "Bencher testbed (--bencher-testbed) is required."
[[ -n "${BENCHER_API_TOKEN:-}" ]]                                         || error -ec "$err_missing_argument" "The BENCHER_API_TOKEN environment variable is required."

exit_if_has_errors

declare artifacts

get_artifacts_path "${benchmark_projects[0]}" artifacts

artifacts_benchmarks_dir=$artifacts/benchmarks
results_dir="$artifacts_benchmarks_dir/results"

# Freeze variables
declare -xr benchmark_project
declare -xr preprocessor_symbols
declare -xr minver_tag_prefix
declare -xr minver_prerelease_id
declare -xr artifacts_benchmarks_dir
declare -xr results_dir
declare -xr bencher_project
declare -xr bencher_testbed
declare -xr bencher_branch
declare -xr bencher_adapter
declare -xri repeat

command -v bencher &> "$_ignore" || error -ec "$err_tool_error" "The 'bencher' CLI was not found on PATH."

exit_if_has_errors

# Re-record each benchmark project $repeat times. Each iteration is an independent process run, so the recorded spread
# captures the real run-to-run variance of the runner -- exactly the history a statistical threshold needs to learn "normal".
declare -i uploaded=0
declare -ri total=$(( ${#benchmark_projects[@]} * repeat ))
declare project

for project in "${benchmark_projects[@]}"; do
    for (( i=1; i <= repeat; i++ )); do
        echo "▶ [$project] run $i of $repeat (Bencher branch '$bencher_branch')..." | to_stdout

        if ! run-benchmarks.sh \
                "$project" \
                --define "$preprocessor_symbols" \
                --minver-tag-prefix "$minver_tag_prefix" \
                --minver-prerelease-id "$minver_prerelease_id"; then
            warning "Benchmark run $i of '$project' failed; skipping the Bencher upload for this iteration."
            continue
        fi

        json_files=("$results_dir"/*-report-full-compressed.json)
        if [[ ! -f "${json_files[0]}" ]]; then
            warning "No JSON results found after run $i of '$project' in '$results_dir'; skipping the Bencher upload."
            continue
        fi

        bencher_args=(
            --project "$bencher_project"
            --token "$BENCHER_API_TOKEN"
            --testbed "$bencher_testbed"
            --adapter "$bencher_adapter"
            --branch "$bencher_branch"
        )
        for f in "${json_files[@]}"; do
            [[ -s "$f" ]] && bencher_args+=(--file "$f")
        done

        # Record-only: deliberately NO --threshold-* and NO --err. We are establishing the baseline, so a noisy point
        # must never fail the job and halt the loop.
        if execute bencher run "${bencher_args[@]}"; then
            uploaded=$(( uploaded + 1 ))
            info "Recorded data point $i of $repeat for '$project'."
        else
            warning "Bencher upload failed for run $i of '$project' (continuing with the remaining runs)."
        fi
    done
done

{
    echo "### 📈 Benchmark history rebuild"
    echo ""
    echo "Projects (${#benchmark_projects[@]}): $(printf '%s ' "${benchmark_projects[@]}")"
    echo "Bencher: **$bencher_project** · testbed **$bencher_testbed** · branch **$bencher_branch**"
    echo "Recorded **$uploaded** of **$total** runs ($repeat per project)."
} | to_summary

(( uploaded > 0 )) || error -ec "$err_logic_error" "No data points were recorded to Bencher."

exit_if_has_errors

args_to_github_output artifacts
