#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Val Melamed

# Validates that all commit messages in a range follow Conventional Commits format.
# Used in CI to enforce commit message discipline.

set -euo pipefail

script_name=$(basename "${BASH_SOURCE[0]}")
script_dir=$(dirname "$(realpath -e "${BASH_SOURCE[0]}")")
lib_dir=$(realpath -e "$script_dir/../../scripts/bash/lib")

declare -xr script_name
declare -xr script_dir
declare -xr lib_dir

# shellcheck disable=SC1091 # Not following: ./gh_core.sh: openBinaryFile: does not exist (No such file or directory)
source "$lib_dir/gh_core.sh"

source "$script_dir/validate-commits.usage.sh"
source "$script_dir/validate-commits.args.sh"

# Allowed commit types — keep in sync with changelog/cliff.prerelease.toml commit_parsers
readonly -a allowed_types=(style build feat test fix refactor perf security docs chore revert remove ci devops)

declare -x base_ref=${BASE_REF:-}

get_arguments "$@"

exit_if_has_errors

# Build the type alternation: feat|fix|perf|...
types_pattern=$(IFS='|'; echo "${allowed_types[*]}")

# Conventional Commits: type[(scope)][!]: description
readonly cc_regex="^(${types_pattern})(\(.+\))?!?: .+"

# Determine the commit range
if [[ -z "$base_ref" ]]; then
    error "No base ref provided. Use --base-ref to specify the comparison point."
    exit_if_has_errors
fi

# Get all commit subjects in the range
declare -i bad=0
while IFS= read -r subject; do
    # Skip merge and revert commits (generated by git)
    if [[ "$subject" =~ ^(Merge|Revert)\  ]]; then
        continue
    fi

    if [[ ! "$subject" =~ $cc_regex ]]; then
        error "Bad commit message: $subject"
        bad+=1
    fi
done < <(git log --format='%s' "${base_ref}..HEAD")

if [[ $bad -gt 0 ]]; then
    echo "" >&2
    info "Expected format: <type>[(scope)][!]: <description>"
    info "Allowed types:   ${allowed_types[*]}"
    info "Examples:        feat: add new glob pattern"
    info "                 fix(parser): handle empty input"
    info "                 refactor!: rename public API method"
    exit 1
fi

info "✅ All commit messages follow Conventional Commits format"
