#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Val Melamed

# Validates that all commit messages in a range follow Conventional Commits format.
# Used in CI to enforce commit message discipline.

set -euo pipefail

script_name=$(basename "${BASH_SOURCE[0]}")
script_dir=$(dirname "$(realpath -e "${BASH_SOURCE[0]}")")
lib_dir=$(realpath -e "$script_dir/../../scripts/bash/lib")

declare -xr script_name
declare -xr script_dir
declare -xr lib_dir

# shellcheck disable=SC1091 # Not following
source "$lib_dir/gh_core.sh"

declare -xri err_argument_value

source "$script_dir/validate-commits.usage.sh"
source "$script_dir/validate-commits.args.sh"

# Allowed commit types — keep in sync with changelog/cliff.prerelease.toml commit_parsers
declare -xra allowed_commit_types

declare -x base_ref=${BASE_REF:-}

get_arguments "$@"
! is_verbose || dump_args "--force"
exit_if_has_errors

# Build the type alternation: feat|fix|perf|...
ifs=$IFS
IFS='|' types_pattern="${allowed_commit_types[*]}"
IFS=$ifs

# Conventional Commits: type[(scope)][!]: description
readonly cc_regex="^($types_pattern)(\(.+\))?!?: .+"

# Determine the commit range
if [[ -z "$base_ref" ]]; then
    error -ec "$err_argument_value" "No base ref provided. Pass it as a positional argument or set \$BASE_REF."
    exit_if_has_errors
fi

# Get all commit hashes and subjects in the range
declare -i bad=0
declare -a bad_hashes=() bad_subjects=()
declare hash subject
while IFS=$'\t' read -r hash subject; do
    # Skip merge and revert commits (generated by git)
    if [[ "$subject" =~ ^(Merge|Revert)\  ]]; then
        continue
    fi

    if [[ ! "${subject,,}" =~ $cc_regex ]]; then
        error -ec "$err_argument_value" "Bad commit message: ${hash:0:8} $subject"
        bad_hashes+=("$hash")
        bad_subjects+=("$subject")
        (( ++bad ))
    fi
done < <(git log --format=$'%H\t%s' "$base_ref..HEAD")

if (( bad > 0 )); then
    branch=$(git branch --show-current)
    # The oldest offending commit's parent is the tightest rebase start point that still
    # surfaces every bad commit in the todo list -- no need to go back to $base_ref itself.
    oldest_bad_parent="${bad_hashes[-1]}^"
    echo "" >&2
    info "Expected format: <type>[(scope)][!]: <description>" \
         "Allowed types:   ${allowed_commit_types[*]}" \
         "Examples        chore(dependencies): update dependencies and lock files"
    info "To fix, copy/paste:" \
         "  git rebase -i $oldest_bad_parent" \
         "Then, in the editor, change 'pick' to 'reword' for each commit listed below, save and close --" \
         "Git opens the message editor for that commit; edit it (e.g. prepend '<type>: '), save and close." \
         "Commits needing reword ($bad):"
    declare -i i
    for (( i = 0; i < ${#bad_hashes[@]}; i++ )); do
        info "  ${bad_hashes[$i]:0:8}  ${bad_subjects[$i]}"
    done
    info "Note: rebase rewrites commit hashes from $oldest_bad_parent to HEAD." \
         "Repeat reword for each commit above in the same rebase session, then force-push:" \
         "  git push --force-with-lease origin $branch"
    exit "$err_argument_value"
fi

info "✅ All commit messages follow Conventional Commits format"
