# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Val Melamed

name: "CI: For now just ping"

# vm2DevOps does not have a true CI workflow yet. This is just a placeholder for future CI jobs.
# For now it is just calling the _ping.yaml reusable workflow.

on:
  workflow_dispatch: {}

jobs:
  call_ping:
    name: "Call Ping"
    uses: vmelamed/vm2.DevOps/.github/workflows/_ping.yaml@main
